// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqVl5XVWevsYNbW1zVal_FDApof0g4W5M',
    appId: '1:710697058216:web:3af9e0fed54dab1e9f679d',
    messagingSenderId: '710697058216',
    projectId: 'nti7-b6572',
    authDomain: 'nti7-b6572.firebaseapp.com',
    storageBucket: 'nti7-b6572.firebasestorage.app',
    measurementId: 'G-GRLXMK93WT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCtLV1jo7jRESaj7vysBXIn5BR0rI7lDc',
    appId: '1:710697058216:android:c442c285d948a9709f679d',
    messagingSenderId: '710697058216',
    projectId: 'nti7-b6572',
    storageBucket: 'nti7-b6572.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2rjyimL0v8-BSAzqD9BFfbjnqZwiNv0E',
    appId: '1:710697058216:ios:15968c72b80ddeb59f679d',
    messagingSenderId: '710697058216',
    projectId: 'nti7-b6572',
    storageBucket: 'nti7-b6572.firebasestorage.app',
    iosBundleId: 'com.example.nti7Fire',
  );
}
